### ISSUE TITLE
Expose item slices from FlatKdTree / FlatVpTree

### ISSUE THREAD

**Issue by RReverser** [tavianator/acap#5]
I want to be able to iterate over all the points in the tree. Since those structures store them as flat arrays, it seems like it would be easy enough to expose a slice reference and let user do whatever they want on the read-only items.

**Comment by RReverser** [comment]
Hm, on the second thought, I guess not as easy because they're wrapped into FlatVpNode. At the very least, an `IntoIterator` on `&FlatVpTree` (to iterate over `&T` rather than consume the instance) should be feasible.

**Comment by tavianator** [comment]
Yeah I was just about to say that.  I did try an implementation with separate `[T]` and `[VpNode]` arrays but it performed worse, and I don't think I'd want to commit to a particular layout anyway.

A `.iter()` method and `IntoIterator<Item=&T> for &Tree<T>` is definitely desirable.  Do you feel like implementing it?  I probably won't have time this week, but I could review a PR.

**Comment by RReverser** [comment]
> Do you feel like implementing it?

I needed that for evaluating performance of VP-tree vs current implementation of my algorithm based on (another) KD-tree crate, but worked around lack of slices and found performance to be exactly the same 😅

So I probably won't be needing this after all, but up to you whether to keep issue open.

**Comment by tavianator** [comment]
Sure, I'll get to this eventually.  I'm planning on some performance improvements too, so maybe keep an eye on this project :)

**Comment by tavianator** [comment]
Fixed by https://github.com/tavianator/acap/commit/81f89229b4b5a1b82814fb7acc1905c0a463a3c6 and https://github.com/tavianator/acap/commit/b1ac058c81a28926e4b97420f9dd95a63a877c55
